name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo on the machine
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependecies    
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "shtambe"


  ui_tests:
    needs: build_unit_test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo on the machine
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependecies    
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install  
    - name: Start the app
      run: npm start &
    - name: Run unit tests
      run: npm run test:ui 

  deploy:
    runs-on: ubuntu-latest
    needs: ui_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true